### ISSUE TITLE
Import and install theme.

### ISSUE THREAD

**Issue by ghost** [NashvilleSoftwareSchool/Cohort7Website#5]
We need to get the theme installed before we do any more content/layout work. @SondaSengupta, you had a theme you found that most people agreed on right? I have no preference and the aesthetic instincts of a baby chimpanzee.  Do you want to go ahead and grab that theme and install it on the site after the #3 skeleton gets pulled in? :bee: :curly_loop:

**Comment by SondaSengupta** [comment]
Already pulled in the request. Going to add the theme within the next hour
or so.

**Comment by SondaSengupta** [comment]
All right, I put in a theme and it's pretty big. I added the _students folder and student collection in the .config file, but that's about it. @colbydehart , can you look over it and see whether I got the student collection thing right and just delete all the stuff you think is unnecessary for a single page app (which is a lot since there are a bunch of gems, don't think we need octo-anything) I didn't delete anything in case you may need it. Its all on the theme branch. 

Oh, and to run it you will have to do "bundle exec jekyll serve"

**Comment by ghost** [comment]
Octopress is just a fork of jekyll with more stuff, Jekyll+ if you will. I think most people who are using Jekyll that i've seen are actually using Octopress. It gives us a few extra things and I've got no problem keeping it in. It all compiles down to flat files anyways so [Short Haiir, Don't Care](#)

**Comment by SondaSengupta** [comment]
Well said. :snail: :shower:

**Comment by SondaSengupta** [comment]
When it all looks good to you, go ahead and pull it in I'd say. :bath:
